### ISSUE TITLE
logo add

### ISSUE THREAD

**Issue by guddubasu** [sayandippaul/dropling-chatapp#10]
I want to add the logo of the chatapp to the top of the sign in page

**Comment by techmannih** [comment]
@guddubasu
I have assigned this issue to you, you can start working on it

**Comment by sayandippaul** [comment]
make the logo visible to all of the pages login,register,settings,chat,contact pae and for all of this pages you have to set  the logo and set title to "DROPLING"


i will set this label for medium due to all of six pages

**Comment by sayandippaul** [comment]
@guddubasu 
how far is your work

**Comment by Sneha123-zudo** [comment]
I am intrested in this issue. Please assign me.

**Comment by techmannih** [comment]
I assigned this issue to @guddubasu two weeks ago. Now, I've assigned it to both of you. Please coordinate on who will raise the pull request first, and I will merge accordingly
