### ISSUE TITLE
Correction in contributing.md file

### ISSUE THREAD

**Issue by techmannih** [sayandippaul/dropling-chatapp#14]
![Screenshot_20240109_170307_Chrome](https://github.com/sayandippaul/dropling-chatapp/assets/125847751/3424f62d-7ff7-4514-bccb-b66ff124ab93)
 
INSTALLATION 
1. Git clone https://github.com/sayandippaul/dropling-chatapp.git
2. cd dropling-chatapp
3. npm install

**Comment by Sneha123-zudo** [comment]
Please assign me this issue , i will do the correction
